spring.application.name=transskribus

whisper.binary-path=/home/ronny/eclipse-workspace/transskribus-projekt/whisper.cpp/build/bin/whisper-cli
whisper.model-path=/home/ronny/eclipse-workspace/transskribus-projekt/whisper.cpp/models/ggml-small.bin
whisper.language=en
whisper.ffmpeg-path=ffmpeg
whisper.lib-path=/home/ronny/eclipse-workspace/transskribus-projekt/whisper.cpp/build/src:/home/ronny/eclipse-workspace/transskribus-projekt/whisper.cpp/build/ggml/src

ollama.base-url=http://localhost:11434
ollama.model=llama3.2:3b
ollama.prompt=Verbessere den folgenden transkribierten Text. Gib mir nur den verbesserten Text, entferne auch alle Füllwörter
